baseURL = "/"
    languageName = "Chinese"
    contentDir = "content/"
    weight = 2
    languageCode = "cn-zh"
    title = "React 源码分析"
    theme = "kraiklyn"
    pygmentsCodeFences = true
    pygmentsStyle = "monokailight" 

[params]

    sidebarColor = "red"
    customCss = []





